- name:  Deploy Artifact
  hosts: localhost
  tasks:

    - name: Copy Jar Artifact to production container server
      shell: scp target/*.jar prod_admin@172.17.0.3:/home/prod_admin/

    - name: Execute/Run the Jar Artifact In Prod
      shell: ssh prod_admin@172.17.0.3 "nohup java -Dserver.port=9090 -jar *.jar" &
