- name: Install Docker and  Deploy Artifact
  hosts: localhost
  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Enable docker service
      shell: service docker restart

    - name: Copy Jar Artifact to docker container
      shell: docker cp target/*.jar Prod_Server:/

    - name: Execute/Run the Jar Artifact In Prod
      shell: docker exec -d -u root Prod_Server sh -c "cd /; java -Dserver.port=9090 -jar *.jar"
