- name: Install Docker and run httpd container
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start docker daemon
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy index.html to docker container
      community.docker.docker_container_copy_into:
        container: Prod_Server
        path: target/*.jar
        container_path: /
