- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Copy JAR file into existing container
      docker_container:
        name: Prod_Server
        state: started
        copy:
          src: target/*.jar
          dest: /

    - name: Execute JAR file in target container
      docker_container:
        name: Prod_Server
        state: started
        command: java -jar target/*.jar
